### ISSUE TITLE
I followed your instructions to get running, but I keep hitting this error...

### ISSUE THREAD

**Issue by jbmaxwell** [anibali/infogan#4]
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init.lua:384: /root/torch/install/share/lua/5.1/trepl/init.lua:384: loop or previous error loading module 'cudnn'

cudnn is up and running on the machine for vanilla tensorflow.

**Comment by anibali** [comment]
After some testing on my own machine I think that this issue may be caused by https://github.com/soumith/cudnn.torch/issues/279. I have updated the Docker image to use a newer version of Lua Torch.

Please try to pull the changes and rebuild the image:

```sh
git pull
nvidia-docker build -t infogan-torch .
```

Hopefully you will then be able to run the training script successfully.

If that doesn't work for you, please post the output of `ls -l /usr/local` so I can check what version of Cuda you are running. Also run `nvidia-docker run -it --rm infogan-torch th -e 'require "cudnn"'` and post the output of that.

**Comment by jbmaxwell** [comment]
Ah! I'm seeing epochs, so it looks like all's well. Thanks!
